BAN_GIFS = [
    "https://tenor.com/bqhVe.gif",
    "https://tenor.com/bsHe5.gif",
    "https://j.gifs.com/y5Pr8z.gif",
    "https://tenor.com/bfvQv.gif",
    "https://j.gifs.com/lO0lv6.gif",
    "https://tenor.com/bGMhb.gif",
    "https://tenor.com/bjZai.gif",
    "https://media.giphy.com/media/fe4dDMD2cAU5RfEaCU/giphy.gif",
    "https://tenor.com/bndta.gif",
    "https://tenor.com/bkyIr.gif",
    "https://media.giphy.com/media/UBqgQxKnUJqb8oZ2zc/giphy.gif",
    "https://media.giphy.com/media/tanIENriCOil3ndF3V/giphy.gif",
    "https://media.giphy.com/media/fwX4RUzdkdx9XUGow4/giphy.gif",
    "https://media.giphy.com/media/XVLfZCU6jDvMYqF1xS/giphy.gif",
    "https://media.giphy.com/media/BSAZJvFOOR0VqREKMg/giphy.gif",
    "https://media.giphy.com/media/CI4aCJUjJDJEj3Jgo4/giphy-downsized-large.gif",
    "https://media.giphy.com/media/0jcrQmPmyI5U532qL2/giphy.gif",
]

KICK_GIFS = [
    "https://tenor.com/bizBJ.gif",
    "https://tenor.com/bjPvj.gif",
    "https://tenor.com/bJMx3.gif",
    "https://tenor.com/bJCGL.gif",
    "https://tenor.com/bsIMJ.gif",
    "https://tenor.com/buURG.gif",
    "https://tenor.com/bNOj9.gif",
    "https://tenor.com/NfK8.gif",
    "https://tenor.com/ymZn.gif",
    "https://tenor.com/77Lu.gif",
    "https://tenor.com/bPD4I.gif",
    "https://tenor.com/bOGXo.gif",
    "https://tenor.com/bDLqs.gif",
    "https://media.giphy.com/media/u2LJ0n4lx6jF6/giphy.gif",
    "https://media.giphy.com/media/BSAZJvFOOR0VqREKMg/giphy.gif",
    "https://media.giphy.com/media/eDR7j2vjCFOUMJ9rT2/giphy.gif",
    "https://media.giphy.com/media/ERNKP5G7ihZNW6VW4Q/giphy.gif",
    "https://media.giphy.com/media/1r6xks2F0iHfbNvt4p/giphy.gif",
    "https://media.giphy.com/media/M7j1rkxm0X5z30Hyrs/giphy.gif",
    "https://media.giphy.com/media/rad9oJzU4hVafD8ZnT/giphy.gif",
    "https://media.giphy.com/media/TcliN5WDKBbnUQ15H3/giphy.gif",
    "https://media.giphy.com/media/y9pfUqY3uaT1MPXxYM/giphy.gif",
]

MUTE_GIFS = [
    "https://media.giphy.com/media/MpCxz9VLh6t8ceRb0r/giphy.gif",
    "https://media.giphy.com/media/HWl1atKEPAWcw/giphy.gif",
    "https://media.giphy.com/media/1xkynOSsb8eFpbEood/giphy.gif",
    "https://media.giphy.com/media/LmUAM5ImMNZd0nnkvn/giphy.gif",
    "https://media.giphy.com/media/JNlXHSSioDe7YGTC7D/giphy.gif",
    "https://media.giphy.com/media/t0iSe43jX8JH0Hb95a/giphy.gif",
    "https://media.giphy.com/media/P4CXV70NTC0umRI61S/giphy.gif",
    "https://media.giphy.com/media/Z0WPxDF7zpIHVPrYUN/giphy.gif",
    "https://media.giphy.com/media/gJS1pGTbXlSCWUe2pg/giphy.gif",
    "https://media.giphy.com/media/SIoetMN7j96O5perEV/giphy.gif",
    "https://media.giphy.com/media/PBZrH2uy9E5rPruuCX/giphy.gif",
    "https://media.giphy.com/media/Cew2qzlug9t3ACYrD5/giphy.gif",
    "https://media.giphy.com/media/PtIm7eUGKYIZbknqsO/giphy.gif",
    "https://media.giphy.com/media/EKbCY8OgdATSGBekxM/giphy.gif",
]

StartPic = [
"https://graph.org/file/f76fd86d1936d45a63c64.jpg",
"https://graph.org/file/69ba894371860cd22d92e.jpg",
"https://graph.org/file/67fde88d8c3aa8327d363.jpg",
"https://graph.org/file/3a400f1f32fc381913061.jpg",
"https://graph.org/file/a0893f3a1e6777f6de821.jpg",
"https://graph.org/file/5a285fc0124657c7b7a0b.jpg",
"https://graph.org/file/25e215c4602b241b66829.jpg",
"https://graph.org/file/a13e9733afdad69720d67.jpg",
"https://graph.org/file/692e89f8fe20554e7a139.jpg",
"https://graph.org/file/db277a7810a3f65d92f22.jpg",
"https://graph.org/file/a00f89c5aa75735896e0f.jpg",
"https://graph.org/file/f86b71018196c5cfe7344.jpg",
"https://graph.org/file/a3db9af88f25bb1b99325.jpg",
"https://graph.org/file/5b344a55f3d5199b63fa5.jpg",
"https://graph.org/file/84de4b440300297a8ecb3.jpg",
"https://graph.org/file/84e84ff778b045879d24f.jpg",
"https://graph.org/file/a4a8f0e5c0e6b18249ffc.jpg",
"https://graph.org/file/ed92cada78099c9c3a4f7.jpg",
"https://graph.org/file/d6360613d0fa7a9d2f90b.jpg",
"https://graph.org/file/37248e7bdff70c662a702.jpg",
"https://graph.org/file/0bfe29d15e918917d1305.jpg",
"https://graph.org/file/16b1a2828cc507f8048bd.jpg",
"https://graph.org/file/e6b01f23f2871e128dad8.jpg",
"https://graph.org/file/cacbdddee77784d9ed2b7.jpg",
"https://graph.org/file/ddc5d6ec1c33276507b19.jpg",
"https://graph.org/file/39d7277189360d2c85b62.jpg",
"https://graph.org/file/5846b9214eaf12c3ed100.jpg",
"https://graph.org/file/ad4f9beb4d526e6615e18.jpg",
"https://graph.org/file/3514efaabe774e4f181f2.jpg",  
"https://graph.org/file/eaa3a2602e43844a488a5.jpg",
"https://graph.org/file/b129e98b6e5c4db81c15f.jpg",
"https://graph.org/file/3ccb86d7d62e8ee0a2e8b.jpg",
"https://graph.org/file/df11d8257613418142063.jpg",
"https://graph.org/file/9e23720fedc47259b6195.jpg",
"https://graph.org/file/826485f2d7db6f09db8ed.jpg",
"https://graph.org/file/ff3ad786da825b5205691.jpg",
"https://graph.org/file/52713c9fe9253ae668f13.jpg",
"https://graph.org/file/8f8516c86677a8c91bfb1.jpg",
"https://graph.org/file/6603c3740378d3f7187da.jpg",
"https://graph.org/file/66cb6ec40eea5c4670118.jpg",
"https://graph.org/file/2e3cf4327b169b981055e.jpg",   

]

birthday_wish = [
    "Wishing you a happy birthday filled with love and joy.",
    "Hope your birthday is as wonderful as you are.",
    "Happy birthday to someone who deserves an exceptional day.",
    "May your birthday be full of surprises and delight.",
    "Wishing you a year filled with new adventures and accomplishments.",
    "May your birthday be as sweet as cake and as joyful as the celebration.",
    "Here's to a fabulous birthday and a year filled with blessings.",
    "Sending you lots of love and warm wishes on your special day.",
    "May your birthday be a time for reflection, relaxation, and joy.",
    "Cheers to another year of making unforgettable memories!",
    "May your birthday be filled with laughter, love, and good times.",
    "Wishing you a birthday that's just as amazing as you are.",
    "Here's to a year filled with love, happiness, and success.",
    "May your birthday be filled with all the love and blessings you deserve.",
    "Sending you warm wishes for a joyful and memorable birthday.",
    "Wishing you a birthday that's as wonderful as you are.",
    "May your birthday be a time to celebrate all the amazing things you've accomplished.",
    "Here's to another year of blessings, love, and adventure.",
    "Sending you lots of love, hugs, and birthday wishes.",
    "May your birthday be full of sunshine, laughter, and good times.",
    "Wishing you a year filled with happiness, success, and love.",
    "Here's to a fantastic birthday and an even better year ahead!",
    "May your birthday be a day filled with joy, love, and celebration.",
    "Sending you lots of love and warm wishes on your special day.",
    "Wishing you a birthday that's as bright and beautiful as you are.",
    "May your birthday be full of love, laughter, and happiness.",
    "Here's to a year filled with exciting adventures and new opportunities.",
    "Wishing you a birthday that's just as amazing as you are.",
    "May your birthday be a time to reflect on all the wonderful things in your life.",
    "Sending you lots of love, hugs, and birthday wishes from afar.",
    "Wishing you a year filled with love, laughter, and all your heart desires.",
    "May your birthday be a time to relax, unwind, and enjoy the company of loved ones.",
    "Here's to another year of blessings, love, and adventure.",
    "Sending you warm wishes for a wonderful and unforgettable birthday.",
    "Wishing you a birthday that's as special and unique as you are.",
    "May your birthday be a time to cherish all the special moments and memories you've created.",
    "Here's to a year filled with joy, laughter, and happiness.",
    "Wishing you a birthday that's just as amazing as you are.",
    "May your birthday be a time to celebrate your wonderful achievements and accomplishments.",
    "Sending you lots of love, hugs, and birthday wishes to make your day extra special.",
    "Wishing you a year filled with love, happiness, and all your heart's desires.",
    "May your birthday be a time to create new memories and cherish old ones.",
    "Here's to another year of blessings, love, and adventure.",
    "Sending you warm wishes for a fabulous and unforgettable birthday.",
    "Wishing you a birthday that's full of love, laughter, and happiness.",
    "May your birthday be a time to appreciate all the wonderful people in your life.",
    "Wishing you a birthday as amazing as you are, filled with joy and memories to last a lifetime.",
    "May your birthday be full of laughter and love, and your year be full of happiness and success.",
    "Happy birthday to someone who makes the world a better place, may all your wishes come true.",
    "Sending you warm birthday wishes and virtual hugs, can't wait to celebrate in person!",
    "May your birthday be as special as you are, surrounded by all the people who love you the most.",
    "Wishing you a day filled with laughter and a year filled with new adventures and opportunities.",
    "Happy birthday to someone who's always there to brighten up my day, may your day be as bright as you are.",
    "Here's to a birthday that's just as awesome as you are, and a year filled with love and happiness.",
    "May your birthday be a time to reflect on all the wonderful memories you've made, and look forward to new ones.",
    "Wishing you a birthday that's full of surprises and excitement and a year filled with new beginnings.",
    "Happy birthday to my favourite person in the world, may your day be as special as you are to me.",
    "Sending you the biggest birthday hugs and all my love, may your day be filled with joy and celebration.",
    "May your birthday be a time to celebrate all your accomplishments and be proud of all you've achieved.",
    "Wishing you a birthday that's as bright and beautiful as you are, filled with love and laughter.",
    "Happy birthday to a true gem, may your day be filled with joy, laughter, and all the things you love.",
    "Here's to a birthday that's full of happiness, excitement, and all the people who make your life special.",
    "May your birthday be a time to let loose and have fun, and your year be filled with growth and success.",
    "Wishing you a birthday that's full of all the things you love and a year that's even better than the last.",
    "Happy birthday to someone who makes my life brighter, may your day be as amazing as you are.",
    "Sending you lots of love and virtual hugs on your special day, may your year be filled with blessings.",
    "May your birthday be a time to cherish all the people who make your life special, and celebrate the person you've become.",
    "Wishing you a birthday that's as unique and wonderful as you are, filled with love and laughter.",
    "Happy birthday to someone who's always been there for me, may your day be filled with joy and celebration.",
    "Here's to a birthday that's full of love, happiness, and all the things that bring you the most joy.",
    "May your birthday be a time to reflect on all the amazing things you've accomplished, and look forward to all that's to come.",
    "Wishing you a birthday that's full of surprises, happiness, and all the things that make you feel alive.",
    "Happy birthday to someone who brings a smile to my face every day, may your day be as wonderful as you are.",
    "Sending you all my love and warmest wishes on your special day, may your year be filled with love and happiness.",
    "May your birthday be a time to appreciate all the people who make your life special, and cherish all the memories you've created.",
    "Wishing you a birthday that's as beautiful as you are, filled with joy and celebration.", ]
